#!/bin/sh

set -e
set -u

ROOT_DIR=$(dirname "$0")

pkg-config --exists --print-errors varnishapi

VARNISHAPI_DATAROOTDIR=$(pkg-config --variable=datarootdir varnishapi)
export VARNISHAPI_DATAROOTDIR

mkdir -p m4
autoreconf -i "$ROOT_DIR"

"$ROOT_DIR"/configure "$@"
