name: build-deb
# Controls when the action will run. 
on:
  push:
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-20.04"
          #- "ubuntu-18.04"
        vrt:
          - 120
          #- 71
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: install build depends
      run: sudo apt-get install python3-docutils python3-sphinx build-essential devscripts debhelper python-docutils dh-autoreconf pkg-config autogen automake autotools-dev autoconf libtool
    - name: install varnish
      run: |
       cd $GITHUB_WORKSPACE
       ./sw_vrt.sh ${{ matrix.vrt }}
       cd debian.vrt
       ./pkg.sh
       ./bf_build_${{ matrix.vrt }}.sh
    - name: build vmod
      run: |
       cd $GITHUB_WORKSPACE
       debclean
       yes | debuild -us -uc
       ls ../

