# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        varnish: 
          - https://github.com/varnishcache/varnish-cache/archive/master.tar.gz
          - https://varnish-cache.org/_downloads/varnish-6.5.1.tgz

# The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run CMake
        env:
          VARSNIH_TGZ: ${{ matrix.varnish }}
      - run: sudo apt-get install python3-docutils python3-sphinx
      - run: |
         wget $VARNISH_TGZ
         tar -zxf *gz
         pushd varnish-*/
         ./autogen.sh
         ./configure --prefix=/usr
         make -sj32
         sudo make install
         popd
      - run: |
         ./autogen.sh
         ./configure --prefix=/usr
         make -j4
         make check -j4
        
