# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        varnish:
          - https://github.com/varnishcache/varnish-cache/archive/master.tar.gz
          - https://varnish-cache.org/_downloads/varnish-6.5.1.tgz
    steps:
    - uses: actions/checkout@v2
    - name: install build depends
      run: sudo apt-get install python3-docutils python3-sphinx
    - name: build varnish
      run: |
       wget ${{ matrix.varnish }}
       tar -zxf *gz
       pushd varnish-*/
       ./autogen.sh
       ./configure --prefix=/usr
       make -sj32
       sudo make install
       popd
    - name: build vmod
      run: |
       cd $GITHUB_WORKSPACE
       ./autogen.sh
       ./configure --prefix=/usr
       make -j4
       make check -j4
        
